### ISSUE TITLE
Slack threads support

### ISSUE THREAD

**Issue by voltapp2** [eul-im/eul#10]
Slack recently implemented embedded threads. They should be supported.

**Comment by mikkelam** [comment]
Any timeline for this? Cant really use slack without it

**Comment by voltapp2** [comment]
@mikkelam this is planned for February 25.

**Comment by noqcks** [comment]
Has this been implemented? 

Looking to utilize Volt, but would require threads.

Thanks!

**Comment by mikkelam** [comment]
Doesn't seem like it, on the website it's on the roadmap for november though

**Comment by voltapp2** [comment]
Fixed in 0.37.
