### ISSUE TITLE
macOS icon looks out of place

### ISSUE THREAD

**Issue by AdamVig** [eul-im/eul#103]
![image](https://user-images.githubusercontent.com/5354752/52718963-a2771080-2f72-11e9-8b87-810cdb4a4f1a.png)

Compared to other icons, the Volt app icon looks huge and clunky. The [macOS Human Interface Guidelines for app icons](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) don't say anything specifically about padding around the icon, but it's clear that icons should not be full bleed.

**Comment by voltapp2** [comment]
Agreed, I will make it transparent and smaller.

**Comment by voltapp2** [comment]
It has been updated, what do you think?

![logo](https://user-images.githubusercontent.com/29845816/52825304-7c5d8780-30bc-11e9-9d15-0b1bc29d6fc0.png)

**Comment by voltapp2** [comment]
Thanks to Leon Kirschner for the improved icon.

**Comment by AdamVig** [comment]
@voltapp That looks much better. I waited to respond because I wanted to test it out, but Volt crashes on open at the moment, so I'll assume that it looks good relative to other app icons.

**Comment by voltapp2** [comment]
@AdamVig can you try to remove cache?

Open Finder,  press Cmd + Shift + G and paste
~/.voltapp

Then delete everything there and try v0.52 again.

**Comment by AdamVig** [comment]
@voltapp I didn't realize there was a new release, so I downloaded that and it started up correctly. I still encountered the crash mentioned in #96 and #98. The icon looks great, though.

edit: By the way, the cache was in `~/.volt`.

**Comment by voltapp2** [comment]
Glad to know you like it!

Releases are going to be daily for the next couple of weeks :)

I’m really close to fixing all those annoying crashes.
