### ISSUE TITLE
macOS won't open

### ISSUE THREAD

**Issue by ceejaywood** [eul-im/eul#108]
Absolutely love the idea!

Downloaded the macOS beta 0.49 version, transfered to /Applications but it won't open.
I'm not to great with computers so would be unsure if something is blocking it or not?

**Comment by JeremyLaurent** [comment]
I have the same issue with 0.51.

**Comment by voltapp2** [comment]
Hi @ceejaywood 

You're not the only one. I'm working on a fix.

**Comment by voltapp2** [comment]
Can you please try 0.53?

https://volt.ws/mac

**Comment by smooney** [comment]
New to Volt and same problem on latest release

**Comment by JeremyLaurent** [comment]
Now it tries to open, closes and then try again indefinitely.

**Comment by voltapp2** [comment]
I found the reason of the crash: an out of bounds array access. V was catching it and silently exiting in prod build.

It was fixed in 0.54. Please restart Volt, it will automatically update to 0.54.

**Comment by JeremyLaurent** [comment]
I updated manually and got the same results (crash, reopen, crash, ...).

**Comment by voltapp2** [comment]
@JeremyLaurent can you please open Terminal, run
`/Applications/Volt.app/Contents/MacOS/volt` and email me the output?

[support@volt.ws](mailto:support@volt.ws)

Thanks

**Comment by bermudalocket** [comment]
Having the same issue. Just emailed you the stack trace from terminal.

**Comment by voltapp2** [comment]
@bermudalocket thanks. 

Now it's a Cocoa crash during window initialization. Working on it.

**Comment by voltapp2** [comment]
@JeremyLaurent @bermudalocket can you please try 0.59?

**Comment by JeremyLaurent** [comment]
I tried 0.60 and got the same results. 

Edit : I have sent you an email with the logs instead

**Comment by JustAPerson** [comment]
FWIW beta 0.66 launches fine for me on macOS 10.13.6.

**Comment by voltapp2** [comment]
Those of you still experiencing crashes, can you please try 0.68?

**Comment by JeremyLaurent** [comment]
Still crashing but it doesn't even show the "Volt has crashed" window. Do you need the logs ?

**Comment by voltapp2** [comment]
@JeremyLaurent yes please.

**Comment by voltapp2** [comment]
I know I've said it a million times, but please try 0.72.

(I wish I could reproduce this crash on my machine)

**Comment by bermudalocket** [comment]
Emailed.

**Comment by JeremyLaurent** [comment]
I just tried 0.73 and it is still crashing

**Comment by voltapp2** [comment]
I found a major memory bug with Valgrind today. Fixed in 0.74. 

By the way, lots of people who previously reported the same crash as yours no longer get it. I’m getting closer :)

**Comment by voltapp2** [comment]
All crashes have been finally fixed. Thank you very much for your help.

**Comment by JeremyLaurent** [comment]
I'm definitely still crashing on 0.78.

**Comment by voltapp2** [comment]
@JeremyLaurent can you try 0.79?

**Comment by voltapp2** [comment]
Oh wait a minute :)

**Comment by voltapp2** [comment]
Try 0.80 @JeremyLaurent 

Thanks

**Comment by JeremyLaurent** [comment]
It works :)
