### ISSUE TITLE
Ability to install Volt without admin rights

### ISSUE THREAD

**Issue by nmrshll** [eul-im/eul#112]
Thanks for this nice project !

When trying to install volt, since I'm not admin on my machine, I dragged the .app into `${HOME}/Applications` in my user's folders instead of the `/Applications` folder that is suggested by default.

Then when trying to launch the app from there, it errors with the message `Plase move Volt to /Applications`. Which I can't do since I'm not admin on my machine.

Would it be possible in a future release to make Volt installable in userspace without admin rights ?

**Comment by voltapp2** [comment]
Hi Nicolas,

Yes, it’s possible. I’ll fix that today.

Thanks for reporting this.

**Comment by nmrshll** [comment]
Awesome ! That was super-reactive, thanks a lot !

**Comment by voltapp2** [comment]
Fixed in 0.68

**Comment by nmrshll** [comment]
Really great ! Thanks a lot !
