### ISSUE TITLE
Slack Authentication Error

### ISSUE THREAD

**Issue by patrickserrano** [eul-im/eul#113]
I just tried to login to the Volt app with Slack and received this message:

<img width="930" alt="screen shot 2019-03-03 at 12 46 12 pm" src="https://user-images.githubusercontent.com/1302453/53699069-6a652f80-3db2-11e9-86dd-9c1fd17bd121.png">

It wasn't happening when I tried logging in on Friday. Did something change since then?

OS: macOS 10.14.3
Volt: 0.68

**Comment by voltapp2** [comment]
Hey @patrickserrano 

This is a macos bug. The auth window is not closed.

 If you go to the main Window, all your chats should be there.

**Comment by patrickserrano** [comment]
@voltapp thanks for the quick reply! Just updated and it looks like it's been sorted out or worked around. Thanks again!
