### ISSUE TITLE
Mouse cursor does not change to a pointer on link hover

### ISSUE THREAD

**Issue by AdamVig** [eul-im/eul#114]
When I hover over a link, I expect the mouse cursor to change from its default arrow to a pointer.

See [this useful guide on mouse cursor states](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Keyword%20values) for visual examples of the different cursor states users will expect to see in this application.

**Comment by voltapp2** [comment]
Fixed in 0.81
