### ISSUE TITLE
Tutorial is difficult to read on macOS in v0.74

### ISSUE THREAD

**Issue by AdamVig** [eul-im/eul#117]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/5354752/53773422-66bbd080-3eb8-11e9-8033-813b13c3be7d.png">

**Comment by AdamVig** [comment]
This may relate to the dark mode being enabled.
I am now finding that I cannot close the tutorial window, too, for what it's worth.
By the way, the settings icon is not styled correctly in dark mode:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/5354752/53774595-23179580-3ebd-11e9-93be-2946251a8ac7.png">

**Comment by voltapp2** [comment]
Sometimes windows can’t be closed. I still haven’t fixed that.

**Comment by voltapp2** [comment]
And yes, this is because of the dark mode. Fixed in 0.76 (not live yet).
