### ISSUE TITLE
Logged in to someone else's account on another Slack team

### ISSUE THREAD

**Issue by AdamVig** [eul-im/eul#118]
I exited Volt 0.73 and let it auto-update to Volt 0.74. After reading the tutorial, I found that I was seeing channels from both my company's Slack team and another team called "gophers" (apparently [this team](https://invite.slack.golangbridge.org/)). I was logged in as somebody named Ivan and could see this person's direct messages with himself. I have never logged into this Slack team, in Volt or elsewhere, nor even heard of it.

I checked `~/.voltapp/settings` and only saw an entry for my company's Slack team, not Gophers. I did, however, see a file `slack_map_gophers_slack_com` in `~/.voltapp` and the chats from that team were present in `~/.voltapp/chats`.

This is obviously pretty weird, but also a potential security/privacy issue.

**Comment by voltapp2** [comment]
Fixed in 0.75.

That was my test account, it only happened in 0.74.

Thanks for reporting.

**Comment by AdamVig** [comment]
@voltapp That Slack team is removed from my list of messaging services, but now the app is crashing sporadically. One time, I waited until the messages loaded (which tool a while), then clicked on one of the channels from the Gophers team and the app immediately crashed.

This may point to a more general bug with removing messaging services, or maybe it's just because the test account was set up in a special way.

**Comment by voltapp2** [comment]
Try deleting local cache in the settings menu,

If you can’t do that, then

Go to ~/.voltapp and remove everything there.

**Comment by AdamVig** [comment]
That worked, thanks.
