### ISSUE TITLE
Cannot paste into password fields when adding account

### ISSUE THREAD

**Issue by valtism** [eul-im/eul#123]
Windows Beta

Cannot paste clipboard into password (or any) fields in login modal.

**Comment by voltapp2** [comment]
Yes, I’m aware of that and unfortunately it’s very hard to fix.

I might have to switch to the recently released Windows 10 web view for this.

**Comment by medvednikov** [comment]
Yes, I’m aware of that and unfortunately it’s very hard to fix.

I might have to switch to the recently released Windows 10 web view for this.

**Comment by gilbertbw** [comment]
I used the AutoHotKey script from [here](https://superuser.com/questions/386846/how-do-you-auto-type-the-contents-of-the-clipboard-from-the-host-into-a-guest-vi) to workaround this problem.

**Comment by medvednikov** [comment]
Sorry for making you do this. Fixing this is a top priority now.

**Comment by deril** [comment]
The same issue I have on MacOS v0.80
