### ISSUE TITLE
Slack: Show and process only channels which I actually joined

### ISSUE THREAD

**Issue by bronestly** [eul-im/eul#15]
Any chance you can replicate the native slack channel list. I am in a Slack with over 200 channels and only want to see those which I am actually member off.

Processing and showing unread message count for all of them just wastes resources.

**Comment by voltapp2** [comment]
Hi @drreen,

Good point. This will be fixed in v0.21, which is going to be live tomorrow.

**Comment by voltapp2** [comment]
This has been fixed in v0.21.

**Comment by voltapp2** [comment]
@drreen you can delete old channels by going to the settings menu, clicking "Delete local data", and re-logging.
