### ISSUE TITLE
Virus in Windows version 0.21

### ISSUE THREAD

**Issue by alinnow** [eul-im/eul#18]
Hello, this version appears to have a virus included. The download archive appears clean, but after running `eul.exe`, it downloads something, which Bitdefender's "Advanced Threat Detection" flagged.

https://www.virustotal.com/#/file/cdbe267d89fc913cd65ad99192306de06fbb9fabacbc05539a76baf1c55ebadc/detection

**Comment by voltapp2** [comment]
Hi @alanpearce 

Thanks for the report, and sorry for the delay.

I'll investigate this. I know one antivirus complains about "seldom downloaded" dlls, since I compile them myself.
