### ISSUE TITLE
notifications are generated even when I sent the message

### ISSUE THREAD

**Issue by ohthehugemanatee** [eul-im/eul#19]
... And the notifications steal focus, too. So every time I press `ENTER` to send a message, I have to click focus back into the window. 

Ubuntu Linux 17.04, i3wm.

**Comment by voltapp2** [comment]
Thanks  for reporting. It will be fixed in v0.22, which is going to be released tomorrow.

**Comment by voltapp2** [comment]
Fixed in v0.22.
