### ISSUE TITLE
3 builds for windows

### ISSUE THREAD

**Issue by gurpreetatwal** [eul-im/eul#2]
Which of the three `.exe` files is the correct build for Windows? Also the website still states "Windows build is temporarily not available. Sorry!"

**Comment by voltapp2** [comment]
Hi @gurpreetatwal,

eul should be downloaded only from https://eul.im

This repo is used for storing the releases and tracking issues. I've removed them from the master branch to avoid confusion.

The Windows build is still unavailable, sorry about that! It's being marked as a virus by Windows 10, I'll be getting in touch with Microsoft to fix this asap.

**Comment by gurpreetatwal** [comment]
Gotcha, thanks for the update!
