### ISSUE TITLE
Preferences not saved in Mac version

### ISSUE THREAD

**Issue by icopp** [eul-im/eul#20]
- Move `eul.app` to `/Applications`
- Open eul
- Use gear icon to open settings menu
- Check one of the boxes and click `Ok`
- Close the app
- Reopen it
- The box you checked isn't checked

**Comment by voltapp2** [comment]
Thanks for the report.

Inline images, emoji, and sounds are not implemented yet. I'll temporarily remove these settings to avoid confusion.

**Comment by voltapp2** [comment]
Fixed in v0.22

Images, emoji, and sound settings are coming next week.
