### ISSUE TITLE
Mac app is unsigned / unidentified

### ISSUE THREAD

**Issue by theontho** [eul-im/eul#22]
You have to go into security settings to be able to to run the app.  Signing the app will make it easier to run & install.

**Comment by theontho** [comment]
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by voltapp2** [comment]
This will be taken care of after September 15.

**Comment by haikuginger** [comment]
Note that it is not necessary to go into security settings; you can right-click (or Ctrl-click) an unsigned application and click Open to run it (you will be prompted to approve the rule exception).

**Comment by r144427** [comment]
Any movement on this one?

**Comment by DewArmy** [comment]
It's long past September 15th. Any updates you can provide to the public?

**Comment by voltapp2** [comment]
@DewArmy sorry for the delay.

The next release will be signed. It will be live in early November.

**Comment by comex** [comment]
This is still an issue with the latest release.  The binary actually has a code signature, but the signer is some certificate from Comodo, whereas the system only trusts Developer ID certificates from Apple.

**Comment by voltapp2** [comment]
@comex To be honest, I was 100% certain that getting a code signing certificate from Comodo would solve this. Let me do some research. 

If getting the Apple Developer ID is the only way, I'll pay for it of course.

**Comment by voltapp2** [comment]
Yes, it's the only way. I'll apply for it asap.

**Comment by comex** [comment]
Thanks!

**Comment by BrianGilbert** [comment]
looking forward to this being closed so I can give eul a try..

**Comment by voltapp2** [comment]
@BrianGilbert the verification process will take from 2 to 5 weeks unfortunately. Apple is not very fast with these things.

**Comment by voltapp2** [comment]
As of v0.34, macOS binaries are signed with a verified Apple Developer certificate.

You can download v0.34 here:

https://github.com/eul-im/eul/releases/download/v0.34/eul_mac.zip
