### ISSUE TITLE
Add eul to homebrew cask

### ISSUE THREAD

**Issue by theontho** [eul-im/eul#23]
It makes it easier to automatically install for all of the nerds and managed workstations out there :)

https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by voltapp2** [comment]
Hi @mahyar 

Good idea! I'll try to submit it today.

**Comment by q69953** [comment]
Any movement on this?
Homebrew is the de facto for install apps on macOS for a lot of people.

**Comment by voltapp2** [comment]
@q69953 I want to get the code signing certificate first. Verification is a ridiculously slow process, but it really should be finished next week.

I'll submit it to homebrew immediately after that.

**Comment by sesam** [comment]
@eul-im how about just using keybase.io, make some PGP or ed25519 keys, and use them for signing?

**Comment by voltapp2** [comment]
eul can now be installed with

`brew cask install eul`

The binary is also signed with a verified Apple Developer certificate.
