### ISSUE TITLE
Windows 7 - Eul 0.21 and 0.22, 0.26 - white main window, white add an account window.

### ISSUE THREAD

**Issue by rluiten** [eul-im/eul#27]
Both windows are totally blank, if i move the mouse over them the mouse cursor changes to the finger pointer for clickable areas, just not rendering looks like.
I am on windows 7 64bit with nvidia graphics card with 350.12 drivers.
Dual screen.

If i hover over the add account window across to the 3rd clickable area from the left (it appears there are 4 in the top row of clickables) and click on it, a window opens to authenticate to slack. 

It appears to let me login and goes back to main window but its still empty all white.

Robin.

**Comment by voltapp2** [comment]
Could you please try it again?

I will receive an error report and be able to investigate this.

**Comment by rluiten** [comment]
Did you want me to grab a new binary or just run the binary I ran before 0.22 ?
I did run the old binary and it appears to have remembered my slack credentials but its blank still

Is there someway i can reset its remembered authentication for slack ?

**Comment by voltapp2** [comment]
I meant running the old binary. This is definitely an issue with rendering. But for some reason I'm not seeing the error message.

What's your CPU/GPU ?

**Comment by rluiten** [comment]
It doesn't appear to error as such, it just does not render.
It appears to be doing stuff, it logs into slack and i can move mouse down left and cllick on channels i know exist the window title changes.

Its a Gigabyte Nvida 970 drivers 350.12 as i mentioned earlier.

**Comment by voltapp2** [comment]
Sorry, I need the CPU model as well.

This sounds like a problem with ANGLE, but this shouldn't really happen on modern hardware and software (Windows 7).

**Comment by rluiten** [comment]
I am at work now, will double check tonight, but I believe it is an i7 6700K, not using the intel gpu for anything.

Since I am at work, testing eul 0.22 here, on a HP Z240 with Windows 10 64bit, it has a Nvidia Quadro K620 and 358.87 drivers, I'll see about trying that revision driver at home soon. Seems to work fine.

I realise you have done this in open gl and probably wrote all the UI controls yourself which is a lot of work. I do realise you are probably fully aware of limitations at the moment, these is not meant as a complaint, just mentioning them so they get considered.

Few initial points now that I can see it logged in with slack :).
1. the text input field Del does nothing (expect delete right character)
2. page up / down keys do nothing in the message area
2. home/end keys do nothing in text input field
3. surprised to see the users "nick" displayed to identify users, it is just not what i am use to seeing as in the web interface i've only seen there account ids
4. cant select text in the text input field with mouse or keyboard

*Verfied it is a i7 6700K*

**Comment by voltapp2** [comment]
@rluiten thanks for the report. Indeed, all UI controls are hand drawn. Only text fields are tricky, and there are a lot of things missing as you noticed. I'll fix them this month.

Are you referring to Slack's @user mentions?

**Comment by rluiten** [comment]
No for 4. i dont mean @user - the user name that shows in the conversation thread at left of posts.
Use to see the "Display name" not the "Full name" of the user.

**Comment by jmlucjav** [comment]
I have this same issue, I log into into slack or skype, and nothing show up. Using v0.25 on windows10

**Comment by arreisGit** [comment]
Same here, using v.0.26 on windows 10 and every time I try to login into slack or skype I got stuck in what seems to be the main screen. http://prntscr.com/h5sch2

**Comment by rluiten** [comment]
@arreisGit I have totally white windows no content at all you have some window content.
I just updated to Latest Nvidia WHQL drivers 388.13 on my Win 7 64bit with Nvidia 970 graphics card and still everything is totally white.

**Comment by voltapp2** [comment]
Fixed in v0.27
