### ISSUE TITLE
Add ability to "unpin"

### ISSUE THREAD

**Issue by ohthehugemanatee** [eul-im/eul#29]
I was so excited about the new "pinning" for channels, and I mis-clicked. I pinned some channels I don't want to pin. The right click menu on a channel doesn't seem to change depending on the pinned state: the option is still "Pin channel".

Ubuntu 17.04 i3wm, eul 0.22.

**Comment by voltapp2** [comment]
Good point, will be fixed today.

**Comment by cbm64chris** [comment]
👍

**Comment by voltapp2** [comment]
Fixed in v0.23
