### ISSUE TITLE
macOS Interface Bugs

### ISSUE THREAD

**Issue by danpalmer** [eul-im/eul#30]
Hey, just thought I'd submit a few bugs and pieces of unexpected behaviour that I've come across while using Eul on a Mac. These are all pretty minor, so submitting as a single issue - feel free to break them up if you want.

 - Text fields do not support word-by-word navigation.
 - Text fields do not support navigate to beginning/end.
 - Text fields do not support selection (by character, word, etc).
 - Text fields do not support select-all hotkey.
 - Text fields do not support copying.
 - Cursor does not render while typing.
 - Scrollbar does not support dragging.
 - Scrolling action defaults to scrolling the channels list, not the main view, when the window is not the focused window, or when newly focused (before clicking on the messages view).
 - Double border on bottom of message text field.
 - Window cannot be resized.
 - Windows do not support tabbing between controls.
 - Notifications do not render fully (https://user-images.githubusercontent.com/202400/30276755-bf5c14e8-96fd-11e7-8835-e5e4231caf8b.png)
 - Notifications do not respect system-wide Do Not Disturb preferences.
 - Notifications are not dismissable (incl. by swiping).
 - Notifications do not show in Notification Center.
 - Notifications look different to all other notifications.
 - Authenticated Slack account does not display full domain name (https://user-images.githubusercontent.com/202400/30277041-8eb843f6-96fe-11e7-81f2-a63a59f960dc.png)
 - Context menu does not support navigation keys (up/down, type to search, close).
 - Does not support system tab bar.

**Comment by voltapp2** [comment]
Hi @danpalmer 

Thanks a lot for the detailed report!

Many of these were already in my  internal backlog.  You can expect all of them to be fixed by the end of the month. Maybe resizing will take a bit longer due to the optimized rendering algorithm.

By the way, the cursor is rendered while typing, it just continues blinking, which shouldn't happen. Good catch!

**Comment by voltapp2** [comment]
All of these were fixed back in February 2018 after switching to a native API (Cocoa).
