### ISSUE TITLE
Can't select all in compose message box in Slack

### ISSUE THREAD

**Issue by alwayscodingsince111970** [eul-im/eul#34]
I can't highlight text via `cmd+a` in the compose message box in Slack.

**Comment by medvednikov** [comment]
Hi @vignesh-sankaran 

Yes, it's a known problem. It will be fixed asap, since this is pretty important for most users.

**Comment by voltapp2** [comment]
Hi @vignesh-sankaran

Yes, it's a known problem. It will be fixed asap, since this is pretty important for most users.

**Comment by voltapp2** [comment]
Fixed in v0.26 (live on Sep 17).
