### ISSUE TITLE
[Slack] Pinning and Unpinning (0.23)

### ISSUE THREAD

**Issue by cbm64chris** [eul-im/eul#35]
Great work and cadence on 0.23. 

Couple of things I have noticed this morning; seems like the unpin chat is working but its a bit erratic.

* On startup the right-click context menu contains "Pin Chat". After the first chat is pinned, the right-click context changes to "Unpin Chat" and remains that way for all future contexts.
* The pinning and unpinning action only works if the pointer is **not** moved after the right-click action.

All tests on MacBook Pro OS X 10.12.6.

I'll continue playing, but again this is really promising!

**Comment by voltapp2** [comment]
Hi @cbm64chris 

Thanks for reporting this.

I can reproduce the pointer bug, but not the first one.

After pinning the first chat, I still get "Pin chat" for all unpinned chats (I'm using macOS). Could you send me a screenshot?  You can send it to support@eul.im if you want.

Thanks

**Comment by cbm64chris** [comment]
Sent the screenshots to the support account.

**Comment by eul-im** [comment]
I haven't received them. Maybe there's a problem with my mail server. Can you try eul.im.alex@gmail.com ?

Thanks

**Comment by voltapp2** [comment]
This has been fixed since only native UI APIs are now used.
