### ISSUE TITLE
Authentication window just signs into the service without authenticating Eul

### ISSUE THREAD

**Issue by matildepark** [eul-im/eul#36]
I'm using macOS version v.0.23.

When I click on the Slack icon, it opens the sign-in for Slack. But it just signs me into Slack's web interface. There is no authentication. The Eul window sits empty after sign-in.

This also happens when I attempt to sign into Facebook; it may be because I use 2FA on Facebook, but it just takes me to the Facebook homepage upon login.

**Comment by voltapp2** [comment]
Hi @sophia-park 

I'm actually working on this issue right now. It will be fixed today in v0.24.

**Comment by AdamDomafoldi** [comment]
Same problem with facebook messenger.

**Comment by voltapp2** [comment]
It's fixed in v0.24. You can download v0.24 for macOS here:

https://eul.im/mac

Autoupdates are temporarily off.

v0.24 for other systems will be released very soon.

**Comment by voltapp2** [comment]
Fixed in v0.25

**Comment by gurpreetatwal** [comment]
I'm stilling having issues with Facebook login using v0.25 on Linux, after entering my credentials I get sent to a page on Facebook stating that "something went wrong". 

I think the OAuth URL might not be constructed correctly? I have built an app using facebook's oauth behavior and only saw that page if messed up the construction of the oauth params.
