### ISSUE TITLE
Accidentally selected HighResolution rendering

### ISSUE THREAD

**Issue by AdamDomafoldi** [eul-im/eul#37]
Hello,

Where could I delete the config files in order to have the default settings? My UI overflows and I cannot use the button, as it is at the bottom. 

Thanks.

**Comment by medvednikov** [comment]
Hi @AdamDomafoldi 

Yes, I'm aware of this bug. I will fix it soon and introduce a shortcut to display the settings window.

What's your OS?

**Comment by AdamDomafoldi** [comment]
Hi @medvednikov,

Thanks for the quick feedback.

My OS: Win 10 x64 Education.

**Comment by voltapp2** [comment]
Hi @AdamDomafoldi,

Yes, I'm aware of this bug. I will fix it soon and introduce a shortcut to display the settings window.

You'll have to delete the following folder:

`C:/Users/[your user]/AppData/eul/db`

Please note that AppData is a hidden folder, so you'll have to use Explorer's path text field at the top.

**Comment by AdamDomafoldi** [comment]
Hi @medvednikov,

Thank you, it works now.

Have a nice day!
