### ISSUE TITLE
Support Signal messenger

### ISSUE THREAD

**Issue by aleksandersumowski** [eul-im/eul#39]
Please consider adding support for [Signal messenger](https://signal.org)

**Comment by voltapp2** [comment]
Hi @aleksandersumowski 

It will definitely be supported, just not right now.

**Comment by aalbertson** [comment]
I'm actually super curious how you'll achieve this and maintain the security/encryption/disassociation that signal provides. Not implying it can't be done, on the contrary, I'm super curious about how that will work!

**Comment by voltapp2** [comment]
I played with it a bit, and indeed it’s hard.

**Comment by aalbertson** [comment]
yeah I can imagine. Maybe you could look at it a different way? Try to build components of volt LIKE Signal, basically rebuild it on the signal protocols and configuration that way you can get the same type of setup, and it could potentially allow signal to slide right in.

**Comment by medvednikov** [comment]
I decided not to implement Signal support after finding out that all alternative clients using official servers are banned for ridiculous reasons:

https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165

I suggest switching to more open platforms.

**Comment by ghost** [comment]
You might want to follow this thread: https://github.com/privacytoolsIO/privacytools.io/issues/779.  There are lots of reasons to avoid Signal.
