### ISSUE TITLE
HiDPI mode

### ISSUE THREAD

**Issue by ohthehugemanatee** [eul-im/eul#4]
Is there any support for HiDPI displays? Any way to set UI scaling?

**Comment by voltapp2** [comment]
Not right now, but it's at the top of the backlog. Will be fixed before the end of the week.

**Comment by ohthehugemanatee** [comment]
lookingn forward to it :)

**Comment by voltapp2** [comment]
Hi @ohthehugemanatee 

Sorry for the delay. HiDPI support is finally there. Go to the options menu to enable it. In later versions HiDPI displays will be detected automatically.

**Comment by niko** [comment]
Is there any way to disable HiDPI without the UI in Linux? I enabled HiDPI on a 1980x1280 display and now it's scaled so large that I can't reach the settings menu any more. I couldn't find a config file in ~/.eul.
