### ISSUE TITLE
linux 32bit build?

### ISSUE THREAD

**Issue by filimonov** [eul-im/eul#41]
was looking for some lightweight client for slack for old pc. Found eul, but binary for linux is build only for 64bit, and i'm getting 

> bash: ./eul_linux: cannot execute binary file: Exec format error

And what's about sources?

**Comment by voltapp2** [comment]
Hi @filimonov 

Good point, I'll set up a 32 bit VM for Linux builds.

I'll let you know once the 32 bit build is live.

The sources are not available yet.

**Comment by voltapp2** [comment]
Unfortunately it was not as simple as I  thought. I'll let you know once I have a 32 bit build.
