### ISSUE TITLE
Source and License

### ISSUE THREAD

**Issue by sumdog** [eul-im/eul#45]
I've noticed the code repository and release files don't contain any source code and there isn't a LICENSE file in your repository either.

Is this project open source or closed/proprietary? Why license is it released under?

**Comment by voltapp2** [comment]
Hi @sumdog 

I want to make it open source and release the code in the near future. I'm not 100% sure it's going to be possible.

**Comment by sumdog** [comment]
Why do you not thing it's possible? What licensing concerns do you have? Do you need help rewriting proprietary code?

**Comment by wodim** [comment]
@eul-im @medvednikov Answer.

**Comment by voltapp2** [comment]
Since I'm getting a lot of questions about this, I'll add detailed info to the landing page today.

**Comment by demurgos** [comment]
I am concerned by the lack of access to the code and absence of explanations.

This application is handling sessions with third party services: these are sensitive data and I cannot trust it in its current state.
