### ISSUE TITLE
Authentication window in minimal goes white when password field is focused

### ISSUE THREAD

**Issue by danielhernik** [eul-im/eul#51]
I'm using Google single sign-on for authentication in Slack. After choosing my workplace and clicking "continue" I can choose between "Sign in with Google" and "I have a guest account". When I click "Sign in with Google" the single sign-on page opens. The moment I focus the password field - everything disappears and the minimal window becomes empty. 
<img width="502" alt="screen shot 2017-10-26 at 10 28 34" src="https://user-images.githubusercontent.com/423913/32042669-a1654c26-ba38-11e7-9263-dc43e098bdf7.png">
<img width="747" alt="screen shot 2017-10-26 at 10 28 44" src="https://user-images.githubusercontent.com/423913/32042675-a4604340-ba38-11e7-872e-583724d58628.png">

**Comment by voltapp2** [comment]
Hi @danielhernik 

Sorry for the delay. Thanks for reporting this, I haven't tested Google sign-in.

**Comment by voltapp2** [comment]
Fixed in v0.27
