### ISSUE TITLE
Windows scaling factor is not used

### ISSUE THREAD

**Issue by chris-morgan** [eul-im/eul#53]
Sure, if you take the trouble to hunt for it, there’s a switch “UI scaling (for HiDPI displays)” in the settings, but this is stuff that *needs* to work automatically. (I would typically have just thrown away the program as unusable on seeing it appearing at half size; I only got as far as prodding around in the settings screen because I was curious what was there, it being prerelease software.)

Moreover, the native scaling factor is not necessarily just 1× or 2×; it can be other figures as well (1.25 and 1.5 are fairly common).

**Comment by voltapp2** [comment]
You are right. This will be fixed.

**Comment by voltapp2** [comment]
This is fixed in v0.29, which will be out this week.
