### ISSUE TITLE
0.26 version crashes after slack sign in, opens slack in a browser window

### ISSUE THREAD

**Issue by pratio** [eul-im/eul#57]
On HighSierra.
Do you have crashlytics integrated?

<img width="1161" alt="screen shot 2017-11-22 at 11 22 56" src="https://user-images.githubusercontent.com/6872952/33122654-1afeb3f2-cf78-11e7-9373-249429a19212.png">

**Comment by josh-sachs** [comment]
experiencing same issue.  The browser window used to log in stays open and just loads slack web... then the app crashes after a few min.  This is on Windows build - windows 10.

**Comment by daniel79** [comment]
Guys any update here?

**Comment by voltapp2** [comment]
Fixed in v0.27
