### ISSUE TITLE
Add a homebrew formula for eul

### ISSUE THREAD

**Issue by Realetive** [eul-im/eul#59]
Add a [homebrew](https://brew.sh/) formula for eul for fast installing and updates.

**Comment by sesam** [comment]
If you ask and get a pre-approval, I can probably cook up the Formula quickly.

Normally homebrew would require more project awareness:
-  at least 20+ are Watchers (currently 6)
- 20+ Forks (currently 0)
- open source would help

There's also the option of getting this in the iTunes App store, though that would require someone to put down some cash and their name for this app, and likely it's breaking some TOS to use some chat apps this way. Which it shouldn't be, but that could be a showstopper both for iTunes and homebrew.

**Comment by sesam** [comment]
Whoops :) See issue #23. Doing a Cask instead of a Formula, is probably the right solution here.

**Comment by Realetive** [comment]
Oh, sorry… Yes, it's duplicate issue. And yes, I meant a Cask =)
