### ISSUE TITLE
Multiple accounts per service

### ISSUE THREAD

**Issue by ohthehugemanatee** [eul-im/eul#6]
I saw this come up in the HackerNews thread (where I found out about Eul, too)... but I didn't see an Issue in here for it yet. It's in the backlog, right?

Personally, this is the killer feature that would let me switch properly, and get all my CPU cycles back! :)

**Comment by voltapp2** [comment]
Correct, it's in the backlog, I just haven't created an issue here. 

What's your personal use case? Do you have multiple Skype accounts?

**Comment by ohthehugemanatee** [comment]
I'm in tech (obviously), which means that I have a thousand Slack organizations. I've reduced it as much as I can, but I still have 3 that I need to keep open at all times.

**Comment by voltapp2** [comment]
This has been implemented for Skype. Slack and Facebook support is coming tomorrow.

**Comment by voltapp2** [comment]
This has finally been implemented for all platforms.

Fixed in v0.26
