### ISSUE TITLE
Option to use installed browser, not embedded browser

### ISSUE THREAD

**Issue by ADTC** [eul-im/eul#60]
I appreciate what you're trying to do. I really do.

But I just can't justify what's happening. First off, it's devious to advertise your product as being lightweight and high-performance _and_ deplore official clients for their use of embedded browsers, _and then_ go behind the backs of your potential users and download an embedded browser of 176 MB in size **without any warning or prior notice**.

At the very least, please put it in your website that you will be downloading an embedded web browser worth 176 MB on top of the 4.7 MB or 7.8 MB eul executable the user is downloading.

![Mockup: An embedded browser (~ 176 MB) will be downloaded when you add an account.](https://user-images.githubusercontent.com/6047296/34069478-34d6cb4e-e278-11e7-930a-80aa119843ca.png)

Also if it's necessary to do authentication through browser web pages, why not simply use the installed browser to do so? Can we have that option to skip downloading a 200 MB embedded browser and just try to use our favorite installed browser to do the authentication? I know it is possible because I have seen tools authenticate that way without any issues.

**Comment by voltapp2** [comment]
Hi @ADTC 

Sorry for the delay.

You are right, this is unacceptable.

Fortunately it has been fixed in v0.27, which is a re-write (that's why it took so long).

The app is now 90 KB and it no longer downloads an embedded browser.

**Comment by ADTC** [comment]
Awesome, thanks!
