### ISSUE TITLE
Eul doesn't start on Linux Mint 18.3

### ISSUE THREAD

**Issue by caiges** [eul-im/eul#61]
./eul_linux 
2017/12/19 22:02:30 Starting eul v0.26...
2017/12/19 22:02:30 DEC took 6.848µs
2017/12/19 22:02:30 DEC took 4.879µs
2017/12/19 22:02:30 DEC took 3.11µs
2017/12/19 22:02:30 DEC took 7.191µs
2017/12/19 22:02:30 gl.Init: glBeginQuery

It appears as if the main window displays for just a second and then disappears.

**Comment by voltapp2** [comment]
This was fixed in the re-written app. It no longer uses OpenGL. It will be out next week.
