### ISSUE TITLE
Program opens but dialogs don't appear

### ISSUE THREAD

**Issue by heysamtexas** [eul-im/eul#65]
So excited to see a native slack app! I really hope you can make this a success. That said, here comes a bug report.

My specific use case is to use this with slack.

I managed to download and run the 0.28 version on OSX. 

OSX Sierra : 10.12.6 (16G29)
Macbook Air 2015

When I click the '+' '?' or the Gear icons, I can see the dialog flash but then disappear instantly.

So, this remains unusable for me at the moment.

If there is anything more I can report then I'm game.

**Comment by Silversunset01** [comment]
I had something similar if it helps (Late 2014 Mac Mini, OSX El Captian 10.11.6) - I ran it the first time and the add service box flashed and disappeared. Then when I reopened it none of the buttons worked at all.

**Comment by voltapp2** [comment]
Hi,

Thanks for reporting this.

I managed to reproduce this on an older macbook. I'll push a fix soon.

**Comment by voltapp2** [comment]
Fixed.
