### ISSUE TITLE
Not out on windows or linux

### ISSUE THREAD

**Issue by damianmcclure** [eul-im/eul#67]
Uhh this is a very big issue but your service still not out on windows or linux pls fix soon

**Comment by DhashS** [comment]
+1. I check the site every once in a while and I keep seeing the date extended a few days into the future.
I'd rather have a statement that you're working on it, rather than the disingenuous "out next week" that I've seen for about a month now

**Comment by damianmcclure** [comment]
It seems they have finally released it for windows, my faith has been restored

**Comment by voltapp2** [comment]
Yes, Windows version was released on March 2. Linux version will be released later this month.

Right now the focus is on fixing bugs, crashes, and implementing crucial missing features.
