### ISSUE TITLE
Virustotal.com - Windows version 0.3: 8 engines detected this file

### ISSUE THREAD

**Issue by domjant** [eul-im/eul#69]
Hello,

According the virustotal.com the Windows version 0.3 most probably contains some suspicious code in the exe file.
https://www.virustotal.com/#/file/af4029913abe8448b3e31046865399fbcb21831e6c218393c47fb634aebca70e/

**Comment by voltapp2** [comment]
Hi @domjant 

Windows binary was not signed correctly.

Should be fine now.
