### ISSUE TITLE
Windows version has multiple issues

### ISSUE THREAD

**Issue by Silversunset01** [eul-im/eul#70]
I can get my windows specs at home, i know offhand its running 64-bit W10 (most likely the home version).
So far the app:
- crashes on launch
- on re-launch tab buttons (to tab between username/password in the slack credentials screen) dont work
- once logged in, wont send/receive messages
- shows all users as a letter string (can provide details later when i'm home) instead of their username
- when clicking on the settings gear / + / ? buttons the app crashes

**Comment by voltapp2** [comment]
Hi @Silversunset01 

Most of these have been fixed in v0.31, which will be live today.

**Comment by jetk** [comment]
@eul-im really rooting for you here, just downloaded the latest Windows version (it reads .30, so if .31 goes up by the time you read this please disregard)

On Slack, user names still are not being displayed but instead we're seeing the .user property of the obj in raw.

64-bit W10 on a Surface Pro 4 i5, 128GB SSD, 4GB RAM

**Comment by eul-im** [comment]
Hi @jetk 

0.31 will be live in a couple of hours.

**Comment by voltapp2** [comment]
All of these have been fixed in 0.36.
