### ISSUE TITLE
Add account UI doesn't appear in wine

### ISSUE THREAD

**Issue by SpaceWhite** [eul-im/eul#71]
Add account UI doesn't show any items just white screen

**Comment by ereli** [comment]
If we knew what dependencies it needs from the windows environment, maybe we could set it correctly.

**Comment by voltapp2** [comment]
Fixed in v0.32 which is not live yet.

**Comment by SpaceWhite** [comment]
Thanks man for the fix @eul-im , I can't wait for the next release :)
