### ISSUE TITLE
Website says Linux version will be out in March but it's April

### ISSUE THREAD

**Issue by IanOlin** [eul-im/eul#75]
The text on the website describing when the Linux version will be released is out of date.

Update: It's now April 6th and the website says out of April 5th

Update: It's now April 12th and the website says out on April 9th

Update: It's now April 16th and the website says version one is out April 15th

**Comment by SpaceWhite** [comment]
I think we have to wait for several weeks I guess because @medvednikov is currently working on linux issues. Btw @medvednikov when is the next release, and when will you make it open source? :D  I'm very excited to hear about it

**Comment by hauau** [comment]
Website now says Linux version will be out on April 9 but it's April 9 already.

Update: It's now April 19, site still says it will be out on April 9.

**Comment by damianmcclure** [comment]
This has been an issue for a while now, The devs should really have a more clear time or just remove the "Out in" because they never seem to meet those expectations

(note: im not trying to diss the devs or anything, just this has been going on for a while)

**Comment by voltapp2** [comment]
Linux  version is finally out. I will post a detailed blog explaining the delay and what has been done to prevent such delays in the future.
