### ISSUE TITLE
The website should have a more reliable file size calculator.

### ISSUE THREAD

**Issue by dertuxmalwieder** [eul-im/eul#76]
First, thank you for eul. We live in a time where developers solve problems by just throwing more hardware at them - every single new C application makes me happy. :-)

However, it seems that the website is not really *dynamic*. While I don't really care (20 KiB more or less don't matter that much), you still might want to consider reading the file size automatically or something.

![What I mean is...](https://user-images.githubusercontent.com/125629/38607159-3558a7c6-3d78-11e8-8fae-89efff1ba3b8.png)

**Comment by voltapp2** [comment]
Hi @dertuxmalwieder 

Sorry for the delay.

You are right, it's not dynamic, and it's been bothering me :)

Everything else about the deployments has been fully automated. I will fix this as well.

**Comment by dertuxmalwieder** [comment]
Thank you!

**Comment by dertuxmalwieder** [comment]
While you're at it: You probably should not provide a download link for a Windows build which is not available for download...

**Comment by voltapp2** [comment]
Fixed in 0.81
