### ISSUE TITLE
The Windows version does not use the proper APPDATA folder.

### ISSUE THREAD

**Issue by dertuxmalwieder** [eul-im/eul#77]
I have just noticed that *eul* has created a `C:\Users\...\AppData\euldata\` folder - which is not where it belongs, it should either be in `\AppData\Roaming\` or `\AppData\Local\`.

**Comment by mentalpiracy** [comment]
Also, it appears that a space character in your User directory name (like "C:\Users\Firstname Lastname\"), causes eul to error, creating the new folder in the same directory as the executable.

**Comment by voltapp2** [comment]
Hi @dertuxmalwieder 

This has been fixed in v0.33.
