### ISSUE TITLE
[Linux v0.33] Doesn't run on Arch Linux

### ISSUE THREAD

**Issue by neongreen** [eul-im/eul#78]
```
$ ./eul_linux 
./eul_linux: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found
(required by ./eul_linux)
```

There is a workaround, though:

```
$ LD_PRELOAD=/usr/lib/libcurl.so.3 ./eul_linux 
```

**Comment by heinrich5991** [comment]
Added as an AUR package, with that work-around: https://aur.archlinux.org/packages/eul.

**Comment by voltapp2** [comment]
Thanks for reporting this and sorry for the delay.

This was fixed.

Unfortunately right now only macOS and Windows versions are available.
