### ISSUE TITLE
[Linux v0.33] Multiple issues with Slack

### ISSUE THREAD

**Issue by neongreen** [eul-im/eul#80]
### 1. Not all channels in the workspace are shown

Subj.

### 2. Some nicks are not resolved

<img width="400" src="https://user-images.githubusercontent.com/1523306/39077862-3e9b714e-4505-11e8-803c-338f5e3c5905.png">

### 3. Monospace is displayed weirdly

<img width="250" src="https://user-images.githubusercontent.com/1523306/39077874-5c518570-4505-11e8-831a-4b9f64c42e7e.png">

### 4. The button panel is sometimes visible and sometimes not

I'm talking about this one:

<img width="250" src="https://user-images.githubusercontent.com/1523306/39077909-aa928a9a-4505-11e8-852f-44cbdf3158ae.png">

### 5. When any button on the button panel is pressed, eul segfaults

Subj.

### 6. Logs are full of warnings about `input string is not valid UTF-8`

```
(eul_linux:5535): Gtk-WARNING **: 01:42:46.709: drawing failure for widget 'GtkWindow': input string not valid UTF-8

(eul_linux:5535): Gtk-WARNING **: 01:42:46.736: drawing failure for widget 'GtkDrawingArea': input string not valid UTF-8

(eul_linux:5535): Gtk-WARNING **: 01:42:46.736: drawing failure for widget 'GtkFixed': input string not valid UTF-8
```

**Comment by neongreen** [comment]
### 7. Scrolling behaves very weirdly

Sometimes I can't scroll up, sometimes I can't scroll down, sometimes messages disappear when I try to scroll, sometimes they appear *only* when I try to scroll, sometimes I scroll down and it scrolls up.

### 8. Not all messages in channels are shown

In some channels there are thousands of messages but I only see the last ~5.

### 9. Search panel's layout overflows

Look at the "P".

<img width="200" src="https://user-images.githubusercontent.com/1523306/39078027-8302d79a-4506-11e8-9146-8d8bd67a8e55.png">

### 10. Sometimes the word "Filter" is not present in the search panel

See above.

**Comment by neongreen** [comment]
NB. I'll be happy to beta-test any upcoming Linux builds :slightly_smiling_face:

**Comment by voltapp2** [comment]
Thanks for the detailed report @neongreen  and sorry for the delay.

Most of this is because of GTK+ issues and my lack of experience with it. 

Linux version is a lot more stable now. Most of these were fixed. Unfortunately right now only macOS and Windows versions are available.

**Comment by voltapp2** [comment]
I'll let you know once it's available again. Definitely this month.
