### ISSUE TITLE
crash on linux after adding slack account

### ISSUE THREAD

**Issue by ShawnTalbert** [eul-im/eul#84]
I added a slack account, which proceeded to display the slack UI in the authentication window (wonky). So I closed the authentication windows and restarted eul.

eul showed me a list of slack channels on that workspace, but if I click any of them the entire app shuts down with nothing written to the bash console.

**Comment by voltapp2** [comment]
Linux version is a lot more stable now. Unfortunately right now only macOS and Windows versions are available.
