### ISSUE TITLE
[Windows v0.35] Crash after console output right after the start on Windows 10

### ISSUE THREAD

**Issue by dertuxmalwieder** [eul-im/eul#86]
Here's what happens when I start `eul.exe` - the newest one - on Windows 10:

- A `cmd` window opens, printing (obv.) debug output:

    HELLO WIN
    eul 0.35 \n
    == 1 49

- The application crashes with no further output. Not even creating a profile directory as far as I can see.

**Comment by voltapp2** [comment]
Sorry for the ridiculous delay. This was fixed.
