### ISSUE TITLE
Download links don't work

### ISSUE THREAD

**Issue by genotrance** [eul-im/eul#89]
Webpage says coming soon but there are download links which don't work.

They point to https://github.com/eul-im/eul/releases/download/v0.35/eul.exe and similar but there's no releases posted on Github, not even older versions to try out.

How can we try out an existing release of Volt?

**Comment by dertuxmalwieder** [comment]
Shouldn't that be *volt.exe* since `eul` seems to have been renamed for whatever reason?

**Comment by SolitudeSF** [comment]
there are no releases, so name doesnt matter anyway.

**Comment by ADTC** [comment]
Looks like this project is abandoned, which is really sad because I was looking forward to trying it again. Slack's web interface eats up sooooo much RAM on Firefox.

**Comment by gervasiocaj** [comment]
@voltapp the mac version is available at the moment, but not the others

**Comment by dertuxmalwieder** [comment]
Yay, it's back! The roadmap is quite behind though.

**Comment by voltapp2** [comment]
I did a terrible job with the development in 2018. Lots of bad decisions and lack of communication.

Sorry about that.

Soon I'll post a detailed blog about what caused the 9 month delay.
