### ISSUE TITLE
OSX: After startup it hangs on "Fetching new messages"

### ISSUE THREAD

**Issue by knx** [eul-im/eul#98]
First startup, displays four seemingly random chanel names in sidebar, then hangs on "Fetching new messages", without anything else happening.

**Comment by voltapp2** [comment]
Hi @knx 

Is the Slack workspace you are testing public?

**Comment by knx** [comment]
Unfortunately no, it's our company internal workspace.

**Comment by barkerja** [comment]
Same happens for me. After start, it begins to load the channels/messages, then the application crashes. Workspace is private.

**Comment by voltapp2** [comment]
I managed to reproduce this, working on a fix right now.

**Comment by voltapp2** [comment]
For now you can just restart the app, it should work fine and have all channels downloaded.

**Comment by barkerja** [comment]
The channels load, but clicking on a channel causes an almost-immediate crash.

**Comment by voltapp2** [comment]
Can you try 0.45?

https://volt.ws/mac

**Comment by barkerja** [comment]
Same issue with 0.45

**Comment by knx** [comment]
I have the same issue, it tries to fetch messages, and then crashes after some time.

**Comment by TristanBrotherton** [comment]
Same issue - also my account is not saved, or present after the crash.

**Comment by medvednikov** [comment]
This is gonna sound stupid. But can you try moving Volt.app to /Applications ?

**Comment by voltapp2** [comment]
This is gonna sound stupid. But can you try moving Volt.app to /Applications ?

**Comment by barkerja** [comment]
Just gave 0.47 a try. Moved the app to `/Applications` (previously I was running the app from `~/Downloads`), still same thing. In addition to no messages loading and then crashing, I now experience the same issue as @TristanBrotherton, having to re-auth on start.

**Comment by TristanBrotherton** [comment]
I am running Volt in /Applications (have been since the start).

**Comment by voltapp2** [comment]
I just found out that macOS limits access to the file system for apps launched from /Downloads.

Moving Volt to /Applications fixed autoupdates and some other bugs, but you still get the crashes.

Does anyone test with a public workspace by any chance?

**Comment by knx** [comment]
I've cleaned every file from the older version, downloaded 0.47, moved it to Applications, launched, authenticated and it did the same thing. I got four seemingly random channel names displayed on the sidebar, then "Fechting new messages" info, then after about a minute it crashed and died. Does it have any kind of debug log or anything I could send to help you with the debugging?

**Comment by voltapp2** [comment]
Please try 0.49.

If you still get crashes, it will send very detailed anonymous crash reports, and I will finally be able to resolve this.

Thanks

**Comment by TristanBrotherton** [comment]
Done. It crashed, as expected. Hopefully you get the logs. Anything I need
to do to send them to you? No prompt was given.

**Comment by voltapp2** [comment]
@TristanBrotherton did it relaunch the app automatically after the crash? If not, can you please open it again. Then I'll get the logs.

**Comment by TristanBrotherton** [comment]
It did not. I have reopened the application (it did not have my prior
connection in there as per the other comments). I'll try the process again.

**Comment by TristanBrotherton** [comment]
Process repeated. It did not re-open so I re-opened it manually. Verified this is 0.49

**Comment by voltapp2** [comment]
All right I'll have to fix the automatic relaunch as well then.

I didn't get the logs.

Something really strange is happening on your system :)

Can you please open the Console app, search for "volt" in the top right corner, click save, then click share by email, and send the logs to support@volt.ws

Thanks a lot. I really appreciate your time.

**Comment by TristanBrotherton** [comment]
I see no logs for Volt in the console.

[image: image.png]

**Comment by voltapp2** [comment]
Unbelievable! One minute

**Comment by voltapp2** [comment]
@TristanBrotherton  can you please open Terminal and run

```
cd /Applications/Volt.app

./Contents/MacOS/volt
```


and paste the output here or send it via email?

Thanks

**Comment by TristanBrotherton** [comment]
That got me logs! Will email the crash logs

**Comment by barkerja** [comment]
Running 0.49. Application starts, then — according to logs — attempts to load channels. Pauses on the 44th for a bit, then crashes.

```
...snip....
2019-02-13 22:20:57.471 volt[11212:15223102] ch 25 / 100
2019-02-13 22:20:57.472 volt[11212:15223102] ch 26 / 100
2019-02-13 22:20:58.427 volt[11212:15223102] ch 27 / 100
2019-02-13 22:20:58.428 volt[11212:15223102] ch 28 / 100
2019-02-13 22:20:59.056 volt[11212:15223102] ch 29 / 100
2019-02-13 22:20:59.793 volt[11212:15223102] ch 30 / 100
2019-02-13 22:20:59.793 volt[11212:15223102] ch 31 / 100
2019-02-13 22:21:00.352 volt[11212:15223102] ch 32 / 100
2019-02-13 22:21:02.769 volt[11212:15223102] ch 33 / 100
2019-02-13 22:21:03.420 volt[11212:15223102] ch 34 / 100
2019-02-13 22:21:03.420 volt[11212:15223102] ch 35 / 100
2019-02-13 22:21:03.421 volt[11212:15223102] ch 36 / 100
2019-02-13 22:21:03.421 volt[11212:15223102] ch 37 / 100
2019-02-13 22:21:04.099 volt[11212:15223102] ch 38 / 100
2019-02-13 22:21:04.099 volt[11212:15223102] ch 39 / 100
2019-02-13 22:21:04.099 volt[11212:15223102] ch 40 / 100
2019-02-13 22:21:05.036 volt[11212:15223102] ch 41 / 100
2019-02-13 22:21:05.608 volt[11212:15223102] ch 42 / 100
2019-02-13 22:21:06.258 volt[11212:15223102] ch 43 / 100
2019-02-13 22:21:06.258 volt[11212:15223102] ch 44 / 100
0   volt                                0x0000000100040d72 f_354 + 34
1   libsystem_platform.dylib            0x00007fff78029b3d _sigtramp + 29
2   ???                                 0x0000000000000024 0x0 + 36
3   volt                                0x000000010003a8c1 f_290 + 785
4   volt                                0x0000000100039c7a f_285 + 1194
5   volt                                0x0000000100029c6b f_280 + 123
6   volt                                0x0000000100016945 f_175 + 725
7   libsystem_pthread.dylib             0x00007fff78032305 _pthread_body + 126
8   libsystem_pthread.dylib             0x00007fff7803526f _pthread_start + 70
9   libsystem_pthread.dylib             0x00007fff78031415 thread_start + 13
2019-02-13 22:21:46.023 volt[11212:15223102] reopen_volt()

/Applications/Volt.app took 1m 25s
```

**Comment by voltapp2** [comment]
Thank you. I figured out the cause of the crash. It crashes when there are too many channels. The file handles are not handled properly. I'll push a fix soon.

**Comment by voltapp** [comment]
There was another related bug that caused an infinite loop for certain channels.

Both of these have been fixed in v0.51. Please try again.

Thanks.

**Comment by voltapp2** [comment]
There was another related bug that caused an infinite loop for certain channels.

Both of these have been fixed in v0.51. Please try again.

Thanks.

**Comment by barkerja** [comment]
Just gave 0.51 a try, still crashing. Logs:

```
...snip...
2019-02-14 11:59:58.919 volt[60561:16460639] ch 44 / 100
2019-02-14 12:00:38.921 volt[60561:16460639] reopen_volt()
```

**Comment by knx** [comment]
I have just tried 0.51 and there is an improvement, the channels have loaded and the app didn't die.
However some channels appear as just a slack icon without any names, and clicking on them does nothing, but I guess this should be opened as another issue.

**Comment by medvednikov** [comment]
Can you please try 0.53?

https://volt.ws/mac

**Comment by voltapp2** [comment]
Can you please try 0.53?

https://volt.ws/mac

**Comment by knx** [comment]
Hi, I just tried the latest version. The channels without names are still there. I tried cleaning the cache and re-adding my slack account again, but it didn't help. Also the app crashed when I was scrolling up in one of the channels. I think it has sent a crash report automatically.

**Comment by voltapp2** [comment]
Can you try 0.66?

**Comment by knx** [comment]
I tried, the nameless channels are fixed and there is no crash. Thanks!

**Comment by voltapp2** [comment]
Cool, thanks a lot for taking the time to test.

**Comment by knx** [comment]
Please let me know if you need any more help with testing, I will be glad to help.
